### ISSUE TITLE
Some cases currently not handled

### ISSUE THREAD

**Issue by alexmojaki** [aroberge/friendly-traceback#101]
Just a few I came across while playing around. Maybe you've already noted them elsewhere.

```
# Likely indicates that they assigned the wrong type to a variable
>>> 3[0]
TypeError: 'int' object is not subscriptable
>>> list(3)
TypeError: 'int' object is not iterable

# Likely if they forget .items() when iterating over a dict
>>> a, b = 3
TypeError: cannot unpack non-iterable int object
>>> a, b = "abc"
ValueError: too many values to unpack (expected 2)
>>> a, b = ""
ValueError: not enough values to unpack (expected 2, got 0)

# Forgot to convert input() to int
>>> "1" * "2"
TypeError: can't multiply sequence by non-int of type 'str'
```

**Comment by aroberge** [comment]
Thanks; I will have to take care of these.

**Comment by aroberge** [comment]
Keeping track of progress.

- [ ] TypeError: 'int' object is not subscriptable
- [ ] TypeError: 'int' object is not iterable
- [ ] TypeError: cannot unpack non-iterable int object
- [ ] ValueError: too many values to unpack (expected 2)
- [ ] ValueError: not enough values to unpack (expected 2, got 0)
- [ ] TypeError: can't multiply sequence by non-int of type 'str'
  - [x] Simply based on recognizing message
  - [ ] More robust by scanning tokens and confirming that multiplication by `str` variable would be valid if `int()` were used.

Also need to add
- [ ] TypeError: can't multiply sequence by non-int of type 'list'
and other similar since
```python
a = [1, 2]
b = "2"
```
`a * b` and `b * a` will yield different messages and yet might be valid expressions if `b` was converted into an integer.

**Comment by aroberge** [comment]
Cases are now all handled. Closing this issue.
