### ISSUE TITLE
missing continuation in multi line string

### ISSUE THREAD

**Issue by gdementen** [aroberge/friendly-traceback#157]
Ok, this is not contest material as it's an IndentationError but well, users would certainly appreciate a more useful error message.

```python
>>> def f():
...     s = "a"\
...         "b"
...         "c"

Traceback (most recent call last):
  File "<friendly-console:32>", line 4
    "c"
   ^
IndentationError: unexpected indent
```

**Comment by aroberge** [comment]
I understand ... and, at the same time, I am not sure of what to do in this case.  

In my opinion, using a final `\` as a continuation character is something that should never been introduced in Python, as it is too error prone with no visual clue when it gives rise to any kind of SyntaxError; for example,  when adding a single space after the final `\`.

In the example you give, I could (should?) identify that it is not an IndentationError since the previous line had the same level of indentation **and** it was not one that was meant to begin a new code block.

That being said, IndentationError are subclasses of SyntaxError and should constitute valid entries for the contest.

**Comment by gdementen** [comment]
In general I think a string not stored in a variable and not part of a module or function docstring is a huge code smell. Not incorrect but... So I suppose bad indentation + string not stored + not a docstring could be detected.

**Comment by aroberge** [comment]
When working using an REPL, I agree that the "string not stored" could possibly be used. 

However, in general, a user will run a program from an editor (https://aroberge.github.io/friendly-traceback-docs/docs/html/editor.html) in which case any SyntaxError and subclasses will prevent code execution.  So, no identification of variables stored (or not), no identification of docstring, etc.  The only remaining clue is examining the source itself, knowing only that Python cannot parse it passed a certain point.

**Comment by aroberge** [comment]
What to you think of the following explanation?

![image](https://user-images.githubusercontent.com/629698/105525643-c17e9100-5cb7-11eb-9f08-121689291d78.png)

**Comment by gdementen** [comment]
The last part is perfect IMO. However, I am not entirely convinced the phrase "The above information is based on what Python told us." helps. I would personally just omit that phrase.

**Comment by aroberge** [comment]
Ok, it makes sense.

In this case, perhaps I should also remove from the old explanation "and does not match the indentation of the previous line".  So, the default explanation would read:
```
The line identified above is more indented than expected.
```
(which could be translated into French, etc.). The addition in this case would then become:
```
However, line 3, which is identified ....
```

**Comment by gdementen** [comment]
That seems great to me.

**Comment by aroberge** [comment]
Closing issue after adding test case.
