### ISSUE TITLE
KeyError when using % string formatting

### ISSUE THREAD

**Issue by Dominik1123** [aroberge/friendly-traceback#162]
```
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> template = '%(a)s'
>>> template % dict(b=1)

Traceback (most recent call last):                                                                                                                                 
  File "<friendly-console:2>", line 1, in <module>                                                                                                                 
    template % dict(b=1)                                                                                                                                           
KeyError: 'a'
```

It would be helpful to explain that all placeholders in the template string need to be covered by the passed dict.

**Comment by aroberge** [comment]
Looking for similar keys was on my todo list ... and I have not done it yet. Once I have implemented it, it would/will still fail to work for the above code since the `dict` is created and immediately discarded, so its content cannot be found by frame inspection. Still, the idea remains valid and I will add it to the list of cases.

So, something like the following would be more reasonable.
```python
>>> template = '%(a)s'
>>> d = {b=1}
>>> template % d
```
