### ISSUE TITLE
SyntaxError: Generator expression must be parenthesized

### ISSUE THREAD

**Issue by Dominik1123** [aroberge/friendly-traceback#174]
If it is not the only function argument, a generator expression must be parenthesized:

```
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> filter(None, i for i in range(5))

Traceback (most recent call last):                                                                                            
  File "<friendly-console:1>", line 1                                                                                         
    filter(None, i for i in range(5))                                                                                         
                 ^                                                                                                            
SyntaxError: Generator expression must be parenthesized
```

There is also a [SO question](https://stackoverflow.com/questions/33137503/generator-expression-must-be-parenthesized-if-not-sole-argument) on this topic.

**Comment by aroberge** [comment]
Type `why()` at the command prompt; is this not an appropriate explanation?

**Comment by Dominik1123** [comment]
Actually I assumed that it didn't recognize the error because no one-line explanation was printed together with the error (the same for #175). This assumption was based on the observation that for some cases Python's error message is basically repeated in the one-line summary; for example:

```
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> None = 1

Traceback (most recent call last):                                                                          
  File "<friendly-console:1>", line 1                                                                       
    None = 1                                                                                                
    ^                                                                                                       
SyntaxError: cannot assign to None                                                                          

You cannot assign a value to None.
```

(By the way, the `why()` explanation reads `None is a constant in Python;`; more precise would be `keyword` instead of `constant`)

So perhaps it would be good to unify this behavior and always print a one-line summary in case the error is recognized?

**Comment by aroberge** [comment]
The one line summary ("hint") is something that I started adding in same cases a short time ago. In some cases, the explanation is indeed essentially rephrasing the error message given by Python. This might seem redundant, except that this additional explanation can then be translated into any language, unlike the message given by Python.  The original goal of Friendly-traceback was (https://aroberge.github.io/friendly-traceback-docs/docs/html/design.html):
```
Friendly-traceback’s primary purpose is to make it easier for beginners
and/or for people that have limited knowledge of English
to understand what caused a program to generate a traceback.
```
Initially, I didn't think that I would be able to do much beyond simply translating/simplifying the information given by Python in the error message.

As for None being a constant rather than keyword, I consider this to be a matter of interpretation. Initially, True and False could be reassigned values, and None was identified a constant. They were not considered to be keywords as such. Eventually they were added as keywords.  In addition, `__debug__` is a constant (set by command line flags) and not a keyword.

**Comment by aroberge** [comment]
I forgot to address a point.  When using Friendly-traceback to execute a script, the information is printed all at once instead of what you see when using the interpreter. Thus the "hint" (one line summary, usually) and the longer explanation are both printed. In some cases, the hint would be essentially identical to the full explanation. To avoid duplication, I chose to not include a one-line summary in such cases.  The decision of whether or not include a one-line summary is something I often struggle with.

**Comment by Dominik1123** [comment]
Okay, I see, since this is the first time I use friendly-traceback and I've been using it via the the friendly console, I didn't know that the one-line summary would be omitted in some of the cases.

Regarding `__debug__` I didn't know you could not reassign to it, I thought this would apply only to keywords. Indeed there does not seem to be a clear separation, as mentioned in the [constants section](https://docs.python.org/3/library/constants.html) of the docs.
