### ISSUE TITLE
How can i help?

### ISSUE THREAD

**Issue by rodrigoejcm** [aroberge/friendly-traceback#2]

**Comment by aroberge** [comment]
First, you could comment on the design document https://aroberge.github.io/friendly-traceback/docs/html/design.html and give me your thoughts.

I note that you are apparently from Brazil - so I suspect that you are fluent in either Portuguese, or Spanish, or both.  One aim of the project is to provide translations into various languages.  Help in this direction would be appreciated.

Right now, there are only 4 cases that are "caught" with explanations given. They can be seen here: https://aroberge.github.io/friendly-traceback/docs/html/tracebacks_en.html That being said, I feel that I should change the wording a bit, including information about Filename and Linenumber where an exception is raised.  I plan to work on this over the next week or so, after which the first translations could be done.  

If translation works interests you, just indicate it and I'll update this issue when I feel there is some work that can be done.   To do translations, I provided these instructions for AvantPy: https://aroberge.github.io/avantpy/docs/html/translations_notes.html

If you wish to help with the code, that would be great too. However, the code that is there currently is just a rough draft written over the course of two days and needs to be reorganized.  I feel that I would need at least one more week for it to be in good enough shape, with a semi-stable structure that others could start contributing to.

Lastly ... what do YOU think you could do to help? :-)

**Comment by aroberge** [comment]
I've done most of the code refactoring needed so that contributions can begin in earnest. The goal: have all Python exceptions (and possibly warnings) covered. A list can be found at the bottom of https://aroberge.github.io/friendly-traceback/docs/html/design.html

For now, SyntaxErrors (and TabErrors) should be excluded, as they need to be dealt with differently.

The model to use is that of `NameError`.  First, create a test file named `raise_some_error.py` containing a single test function, something like the first test function in https://github.com/aroberge/friendly-traceback/blob/master/tests/raise_name_error.py

Before going further, it might be worth creating an issue and mentioning that you are working on `SomeException` to avoid duplicated and wasted efforts.

It should contain similar code so that it can run on its own.

Next, create a file to catch the error, similar to https://github.com/aroberge/friendly-traceback/blob/master/tests/catch_name_error.py but without the `test_flush()` function, which does not need to be replicated anywhere else; I might separate out at some point.

Next, we need to provide some generic information about that exception. This is done in https://github.com/aroberge/friendly-traceback/blob/master/friendly_traceback/generic_info.py

Based on the information given, if one can give more specific information about the error raised, it should be added in https://github.com/aroberge/friendly-traceback/blob/master/friendly_traceback/specific_info.py

If anyone reaches that stage, it will likely be time for a pull request ... and for me to add this type of information to the documentation, if I have not done so already.

**Comment by aroberge** [comment]
@rodrigoejcm Please see #3
