### ISSUE TITLE
Unclosed brackets SyntaxErrors

### ISSUE THREAD

**Issue by auscompgeek** [aroberge/friendly-traceback#20]
An extremely common case I see beginners trip up on is an unclosed bracket, such as:

```python
x = int('1'
if x == 1:
  print('yippee')
```

This is the worst case of this type, as the CPython parser will start and fail to parse a ternary expression, pointing to the colon! The same issue arises with for loops (where they would begin a generator expression or comprehension).

```pytb
  File "/tmp/test.py", line 2
    if a == 1:
             ^
SyntaxError: invalid syntax
```

Other tokens are slightly less bad here, where the error will point to the end of the first token:

```python
x = int('1'
while x == 1:
  ...
```
```pytb
  File "/tmp/test3.py", line 2
    while a == 1:
        ^
SyntaxError: invalid syntax
```

[PyPy has a significantly nicer error message for this entire scenario:](https://morepypy.blogspot.com/2018/04/improving-syntaxerror-in-pypy.html)
```pytb
  File "/tmp/test.py", line 1
    a = int('1'
           ^
SyntaxError: parenthesis is never closed
```

**Comment by aroberge** [comment]
Thank you for the suggestion.  It is something I had started to implement in a different project (see https://aroberge.github.io/avantpy/docs/html/tracebacks_upper.html#mismatchedbracketserror and the subsequent case). As you point out, this is something quite common for beginners and I should give it a higher priority; I had not done so yet because it really requires a different parsing strategy than what I use for other cases.  Since I have a bit of free time today, I'll take a stab at it and post an update here for comments.

**Comment by aroberge** [comment]
Could you have a look at the three new cases starting at https://aroberge.github.io/friendly-traceback-docs/docs/html/syntax_tracebacks_en_3.7.html#syntaxerror-unmatched-closing-parenthesis
and let me know what you think?

Two of these have different and more informative error message **from Python itself** when using Python 3.8. https://aroberge.github.io/friendly-traceback-docs/docs/html/syntax_tracebacks_en_3.8.html#syntaxerror-unmatched-closing-parenthesis

**Comment by auscompgeek** [comment]
Huh, I didn't know CPython 3.8 has a specific error message for mismatching brackets. I should take the chance to test 3.8 beta at some point.

Looks good!
