### ISSUE TITLE
Accept command line script parameters

### ISSUE THREAD

**Issue by JulienPalard** [aroberge/friendly-traceback#50]
In hackinscience.org when I check the student code I run:

```python
proc = subprocess.run(
    [
        "python3",
        "-m",
        "friendly_traceback",
        "--formatter",
        "correction_helper.friendly_traceback_markdown",
        "solution.py",
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    universal_newlines=True,
)
```

Which give them, on error, a nice Markdown output that get properly rendered and colored in the front-end, lovely.

But for some exercises I would like to pass them arguments, but it does not look supported yet. I may have time to take a look at it by myself, but probably not today, so as a first step I'm writing this issue :)

**Comment by aroberge** [comment]
If I understand correctly: you would like to have something like an `--user-defined` command line argument for friendly_traceback; this extra argument would be passed added to `info` created in `core.get_traceback_info` and passed along to whatever formatter is
chosen - presumably a user-defined one, since we'd want a formatter that could make sense of this new information.

Is this correct?

If so, in addition to parsing and storing the extra command line argument, in core.py, instead of 
```python
    try:
        session.traceback_info = info = get_traceback_info(
            etype, value, tb, session.write_err
        )
        explanation = session.formatter(info, level=session.level)
    except FriendlyException as e:
        session.write_err(e)
        return
    session.write_err(explanation)
```
we'd want something like
```python
    try:
        session.traceback_info = info = get_traceback_info(
            etype, value, tb, session.write_err
        )
        if session.user_defined_argument is not None:    # adding this block
            info["user-defined"] = session.user_defined_argument
        explanation = session.formatter(info, level=session.level)
    except FriendlyException as e:
        session.write_err(e)
        return

    session.write_err(explanation)
```

**Comment by aroberge** [comment]
I think I might have misunderstood.  Perhaps what you mean is to be able to do the equivalent of
```
python solution.py arg1 arg2 ...
```
and pass these arguments to friendly_traceback: these are to be used by the user's program and NOT by friendly_traceback.

I can definitely look at doing either one of these possibilities. I might have some time to do so this weekend.

**Comment by JulienPalard** [comment]
Your 2nd interpretation is the one I was trying to explain (flagged accordingly with +1 and -1).

Prepending a `.install()` call would work as a "temporary fix", nice spot! But the "off by 4" lines is not really OK.

I don't know how it mixes well or not with argparse.

basic idea is to be able to write:

    python solution.py arg1 arg2 ...

as:

    python -m friendly_traceback solution.py arg1 arg2

But I bet argparse could mis-understand this if we happen to have say "--formatter" as arg1. Maybe it could be disambiguated using the typicall `--` meaning "being of non-option parameters" (hope it's implemented in argparse, did not checked yet), so maybe:

    python -m friendly_traceback solution.py -- arg1 arg2

**Comment by aroberge** [comment]
Bad news/ possibly good news.

First the bad news: Friendly-traceback uses Python's runpy module to run user scripts. As far as I know, this does allow any way to pass on arguments to the user's program. See https://docs.python.org/3/library/runpy.html#runpy.run_path for details.

However ...

Using a .pth file, it appears possible to install a program like friendly-traceback so that it is used by default instead of Python's standard tracebacks. This is what better-exceptions does (https://github.com/Qix-/better-exceptions).  If that could be made to work, it might be a possibility.

Another, possibly better option might be to define a site.py file that does the same thing.  A similar, but slightly less drastic option, is to use a usercustomize.py file. I'll try to find the time to test this tomorrow.  (https://docs.python.org/3/library/site.html)

**Comment by aroberge** [comment]
![image](https://user-images.githubusercontent.com/629698/88446538-32281c00-ce01-11ea-9497-ec5ca2f5738a.png)

Using Windows
1) ensure that the current directory is on the main Python path
2) Note that running test.py resulted in a traceback being processed by friendly_traceback
3) `test.py` contains a single line; nothing about friendly_traceback is found there.
4) in the current directory, I also have a file named `usercustomized.py` whose content is used to "install" friendly_traceback to use it as an exception hook instead of the standard Python one.

**Comment by JulienPalard** [comment]
It may be simpler than that, as `run_path` does not starts a new interpreter, the `sys` module from both will be shared.

So something like
```
try:
    old_argv = sys.argv
    sys.argv = [old_argv[0], *args]
    runpy.run_path(target_script)
finally:
    sys.argv = old_argv
```

should be enough. run_path will edit sys.argv[1] so we don't care about it here. Backuping `sys.argv` is probably useless though.

I'm trying it with friendly-traceback.
